# Generated by Django 5.2.6 on 2025-09-29 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fighter_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=48)),
                ('Weight_class', models.CharField(max_length=48)),
                ('Age', models.PositiveSmallIntegerField(max_length=48)),
                ('Prof_record', models.PositiveBigIntegerField(max_length=48)),
            ],
        ),
    ]
