# Generated by Django 5.2.6 on 2025-09-29 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muaithai', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter_details',
            name='Age',
        ),
        migrations.RemoveField(
            model_name='fighter_details',
            name='Prof_record',
        ),
    ]
