# Generated by Django 5.2.6 on 2025-09-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaithai', '0002_remove_fighter_details_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter_details',
            name='Age',
            field=models.PositiveSmallIntegerField(default=25),
        ),
        migrations.AddField(
            model_name='fighter_details',
            name='Prof_record',
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
