# Generated by Django 5.2.6 on 2025-09-29 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaithai', '0003_fighter_details_age_fighter_details_prof_record'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter_details',
            name='Prof_record',
            field=models.CharField(default=0),
        ),
    ]
