# Generated by Django 5.2.6 on 2025-09-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaithai', '0004_alter_fighter_details_prof_record'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter_details',
            name='Image',
            field=models.ImageField(blank=True, null=True, upload_to='fighters/'),
        ),
    ]
