# Generated by Django 5.2.6 on 2025-09-30 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaithai', '0005_fighter_details_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter_details',
            name='Prof_record',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
