# Generated by Django 5.2.6 on 2025-10-01 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaithai', '0006_alter_fighter_details_prof_record'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=120)),
                ('image', models.ImageField(blank=True, null=True, upload_to='fighters/')),
            ],
        ),
    ]
