# Generated by Django 5.2.6 on 2025-10-01 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaithai', '0007_carousel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='description',
            field=models.CharField(max_length=240),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='title',
            field=models.CharField(max_length=90),
        ),
    ]
