# Generated by Django 5.2.6 on 2025-10-16 05:02

from django.db import migrations, models
import datetime


class Migration(migrations.Migration):

    dependencies = [
        ('muaithai', '0008_alter_carousel_description_alter_carousel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter_details',
            name='created_at',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 10, 16)),
            preserve_default=False,
        ),
    ]
