# Generated by Django 5.2.6 on 2025-10-16 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('muaithai', '0010_alter_fighter_details_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fighter_details',
            name='created_at',
        ),
    ]
