# Generated by Django 5.2.6 on 2025-10-16 05:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaithai', '0011_remove_fighter_details_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter_details',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
