# Generated by Django 5.2.6 on 2025-10-20 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaithai', '0012_fighter_details_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='fighter_details',
            name='p4p_rank',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
