# Generated by Django 5.2.6 on 2025-10-22 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('muaithai', '0013_fighter_details_p4p_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fighter_details',
            name='Age',
            field=models.PositiveSmallIntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='fighter_details',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='fighter_details',
            name='p4p_rank',
            field=models.IntegerField(default=99, null=True),
        ),
    ]
